# Site settings
title: Hower World
description: 不会写湿的摄影狮不是一个好的程序猿

# User settings
username: whatwhyhow7
nickname: 沃特 · 歪 · 豪 · 塞翁
user_title: Software Developer
email: wangwenhao.rar@gmail.com

exclude: ['package.json', 'src' , 'node_modules']
