# Site settings
title: Hower's Homepage
description: TALK IS CHEAP, SHOW YOU WHO AM I
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: whatwhyhow7
nickname: 沃特 · 歪 · 豪 · 塞翁
user_title: Software Developer
email: wangwenhao.rar@gmail.com
github_username:  whatwhyhow7
# twitter_username: lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
