# Site settings
title: Hower World
description: TALK IS CHEAP, SHOW YOU WHO I AM
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: whatwhyhow7
nickname: 沃特 · 歪 · 豪 · 塞翁
user_title: Software Developer
email: wangwenhao.rar@gmail.com
github_username:  whatwhyhow7

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
